version: '3.8'

services:
  han-viet-app:
    build: .
    ports:
      - "5008:5008"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      # Mount logs directory nếu cần
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5008/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 