services:
  - type: web
    name: han-viet-search-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 5008
    healthCheckPath: /api/health
    autoDeploy: true 